apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    env: metrics
spec:
  selector:
    matchLabels:
      env: metrics
  template:
    metadata:
      name: prometheus
      labels:
        env: metrics
    spec:
      containers:
      - image: prom/prometheus
        name: prom
        args:
        - '--config.file=/opt/prometheus.yml'
        - --storage.tsdb.path='/opt/prometheus_data/
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: prometheus-persistent-storage-store
          mountPath: /opt/prometheus_data
        - name: prometheus-script
          mountPath: /opt/prometheus.yml
          subPath: prometheus.yml  
      volumes:
      - name: prometheus-persistent-storage-store
        persistentVolumeClaim:
          claimName: prom-storage-pvc-claim
      - name: prometheus-script
        configMap:
          name: prom-config