apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc-reclaim
  labels:
    vol: prom-storage
    type: local
spec:
  storageClassName: xclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi