apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc
  labels:
    vol: prom-storage
    type: local
spec:
  StorageClass:  xclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi