apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc
  labels:
    vol: prom-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/prometheus_data"
  resources:
    requests:
      storage: 1Gi