apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-vol0
  namespace: default
spec:
  storageClassName: xclass
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hostpath-vol0-source-path"
    type: DirectoryOrCreate