apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-storage
  namespace: default
spec:
  storageClassName: xclass
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/prometheus_data/"
    type: DirectoryOrCreate