apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-storage
  namespace: default
spec:
  storageClassName: xclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/prometheus_data/"
    type: DirectoryOrCreate